version: '2.1'

services:
  zuul-db:
    image: zuul-db
    build: .
    restart: always
    environment:
          - JAVA_OPTS=-Dfile.encoding=UTF-8 -Dlogging.path=/var/log/project/cmadmin -Dlogback.loglevel=DEBUG -Xmx400M
          - SPRING_BOOT_OPTS= --server.port=9001 --spring.datasource.url=jdbc:mysql://192.168.0.88:3306/test --spring.datasource.username=root --spring.datasource.password=cmadmin
    ports:
      - 80:9001
