server:
  port: 8888
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://192.168.1.88:3306/shang
    username: root
    password: shang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
zuul:
  routes:
    book:
      url: http://www.baidu.com
      stripPrefix: false
#debug: true