server:
  port: 8888
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/shang
    username: root
    password: shang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
zuul:
  routes:
    books:
      path: /hello/**
      url: http://www.baidu.com
#debug: true