server:
  port: 8888
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://192.168.0.88:3307/test
    username: root
    password: cmadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
zuul:
  ignore-security-headers: false
#debug: true