server:
  port: 4455
ribbon:
  okhttp:
    enable: true
spring:
  datasource:
    url: jdbc:mysql://192.168.1.88/shang
    username: root
    password: shang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update